site_name: KTSynologyDDNSCloudflareMultidomain Documentation
site_url: https://github.com/mrikirill/KTSynologyDDNSCloudflareMultidomain
repo_url: https://github.com/mrikirill/KTSynologyDDNSCloudflareMultidomain
site_author: mrikirill
site_description: Native DDNS Cloudflare agent for Synology DSM and SRM with support for multidomains and subdomains
theme:
  name: material